<!DOCTYPE html>
<?php

//$import->csvToArray();
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form_element">
    <?php echo $this->formRow($form->get('myfile')) ?>
</div>
<br>
<div class="form_element">
    <?php echo $this->formRow($form->get('upload')) ?>
</div>
<br>
<div class="form_element">
    <?php echo $this->formRow($form->get('import')) ?>
</div>
<?php
echo $this->form()->closeTag();
$upload->uploadFile();
$import->importCSV();
?>
<br>
<?php
